### ISSUE TITLE
Primary Tabs

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/styleguide#11]
Very useful documentation.
I see that Vertical Tabs are included.
How about the horizontal Primary Tabs? I.e. the one that say 'Bartik' and 'Seven' when I view the styleguide.

**Comment by wesruv** [comment]
Great catch!

**Comment by ghost** [comment]
> the one that say 'Bartik' and 'Seven' when I view the styleguide.

Those *are* the primary tabs. Just refer to them when styling or comparing themes.
There's no point duplicating them below.
