### ISSUE TITLE
Think we have some PHP errors

### ISSUE THREAD

**Issue by wesruv** [backdrop-contrib/styleguide#15]
![image](https://cloud.githubusercontent.com/assets/5607236/18038084/d4f3aec8-6d60-11e6-94ba-76d83d9f7dde.png)

![image](https://cloud.githubusercontent.com/assets/5607236/18038086/db4f7946-6d60-11e6-8144-2ede36714597.png)

**Comment by ghost** [comment]
I believe these have since been fixed. Feel free to re-open with some additional information if that's not the case.
