### ISSUE TITLE
Include in core?

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/styleguide#16]
I've been thinking about this for some time now. Wouldn't this be a nice inclusion for core? It would improve TX if we for example had a "style guide" link available for all themes so that themers can easily work on (sub)theming.

Also, I was thinking a similar link in the themes section of backdropcms.org so that people that want to choose a theme can have a better idea of what the theme looks like. Although that might mean that backdropcms.org would need to have installed **all contrib themes** (not good). They are not many now, but we might grow to be as big as d.org one day. Perhaps a themes.backdropcms.org subdomain?

If we do implement something like that somewhere online where people can see what the available themes look like in reality, it'd be great. We might include "preview" links for each theme in the Project Browser too.

Anyways, point is that the theme screenshot we provide is not enough to help people a make decision as to which them to go with. I often have to install a theme, enable it, then see it is not a good fit, then disable/remove, then repeat. Not good UX.

Just thinking out loud here.

**Comment by ghost** [comment]
Since this has since been discussed and dismissed in https://github.com/backdrop/backdrop-issues/issues/3240, I'm going to close this issue.
