### ISSUE TITLE
Offer to maintain

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/styleguide#27]
I'd like to offer to help maintain Styleguide. I've posted some issues and PRs I can merge, and possibly work on some other stuff in the queue.

I know there's already 3 maintainers here, but since there's been no commits for over 2 years, maybe y'all need some more help...? 😉

**Comment by jenlampton** [comment]
Yes please! Most of our work here was done for backdropcms.org, and then for the Basis theme, and it hasn't been active for a while. We'd love to have you on board!
