### ISSUE TITLE
Use real-world examples wherever possible

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/styleguide#3]
Designers may have a hard time designing (or styling) in a vacuum.  Where possible, it would be great if we could use real examples (markup and text) of how each item is used in core. 
- [x] status messages
- [x] links inline (use node as an example)
- [ ] dialog (use confirm form as example)
- [ ] other places?

**Comment by jenlampton** [comment]
Update: I've updated the status messages to use real messages from core. Will look for other places to update as well.

**Comment by ghost** [comment]
The 'FORMATTING OPTIONS' section of a textarea field looks different between the styleguide and node forms...

**Comment by ghost** [comment]
I've unticked the 'Status messages' above as messages with lists render slightly differently:

Backdrop:
```html
<div class="messages error">
  <h2 class="element-invisible">Error message</h2>
  <ul>
    <li><em class="placeholder">Notice</em>: Undefined index...</li>
    <li><em class="placeholder">Notice</em>: Undefined index...</li>
  </ul>
</div>
```

Styleguide:
```html
<div class="messages error">
  <h2 class="element-invisible">Status message</h2>
  <div class="item-list">
    <ul>
      <li class="odd first">You are not authorized to post comments.</li>
      <li class="even last">Cron run failed.</li>
    </ul>
  </div>
</div>
```
Note the addition of `<div class="item-list">` and `class="[classes]"` in the styleguide...

**Comment by ghost** [comment]
I made a commit that replaces the 'filter tips' with a 'text format' field (that has the tips in a fieldset below it).

**Comment by ghost** [comment]
And this commit makes the messages match the formatting of the real site messages.

**Comment by ghost** [comment]
Inline links look fine (compared markup with node), so ticked them off the list above.

As for dialog, I don't believe we have a confirmation form in a dialog in core...

Based on the age of this issue, I'm going to close it now. But if there are still issues or things that can be improved we can open separate issues in future.
