### ISSUE TITLE
Style Guide Palette is incompatible

### ISSUE THREAD

**Issue by Wylbur** [backdrop-contrib/styleguide#30]
![2022-12-09_13-17-style-guide-error](https://user-images.githubusercontent.com/238274/206780567-281cf75b-6101-4259-8b6a-1b50ea3c5900.jpg)

I get this error on the module list page with styleguide installed on my site.  I can take a look at this issue, probably just need to update the info file.

**Comment by izmeez** [comment]
Same issue noted. This appears to be a duplicate of issue #1.

**Comment by Wylbur** [comment]
This is a duplicate of #1 .  Closing this in favor of that task.

**Comment by Wylbur** [comment]
Closing
